name = "Maddy Origins SMP Redux"
author = "Maddy"
version = "0.2.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ae3d14f2cd928e1ee48ce94732b61155f1e0f8559051dfa08f142bfe3cc0bead"

[versions]
fabric = "0.17.2"
minecraft = "1.21.1"
unsup = "1.1.6"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
