name = "Maddy Origins SMP Redux"
author = "Maddy"
version = "1.0.12"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9f7af40209865862f94496e209f9855a65254c1588c5e1950f8e2ea1dfea4e5a"

[versions]
fabric = "0.17.2"
minecraft = "1.21.1"
unsup = "1.1.6"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
