name = "Maddy Origins SMP Redux"
author = "Maddy"
version = "0.1.82"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7106752c96c6706ab9409b0986586f7203eef17819ec293da239487cfbf5f0b8"

[versions]
fabric = "0.17.2"
minecraft = "1.21.1"
unsup = "1.1.6"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
