name = "Maddy Origins SMP Redux"
author = "Maddy"
version = "0.1.64"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e65ce2baaf8c7620e945c8dc66a4709be622835cbf9eb535a2d1e9aad4786733"

[versions]
fabric = "0.17.2"
minecraft = "1.21.1"
unsup = "1.1.6"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
