name = "Maddy Origins SMP Redux"
author = "Maddy"
version = "0.1.83"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ced0517adb71fa8c4e7f0aeb4e47e26b32a4f2ef7c8060994760d63524763617"

[versions]
fabric = "0.17.2"
minecraft = "1.21.1"
unsup = "1.1.6"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
