name = "Maddy Origins SMP Redux"
author = "Maddy"
version = "0.2.12"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "78c2fd835507c084d9475725f426a9d37c1486b9fdd32a9b4acd20fcaf94a8a0"

[versions]
fabric = "0.17.2"
minecraft = "1.21.1"
unsup = "1.1.6"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
