name = "Maddy Origins SMP Redux"
author = "Maddy"
version = "0.2.10"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "731c9ebe74a51b6079e578b641254755290af7077d01c2d2789d48b35a6e7d86"

[versions]
fabric = "0.17.2"
minecraft = "1.21.1"
unsup = "1.1.6"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
