name = "Maddy Origins SMP Redux"
author = "Maddy"
version = "1.0.18"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9e70dfd3a12d683223e473111f4a2783a0f38fbb2d555c96700e9f83b0bc06f6"

[versions]
fabric = "0.17.2"
minecraft = "1.21.1"
unsup = "1.1.6"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
