name = "Maddy Origins SMP Redux"
author = "Maddy"
version = "0.1.54"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d3fbae6c12d66d7d11f797ea20de13caf30f53f2fc451315d05213026e646a3e"

[versions]
fabric = "0.17.2"
minecraft = "1.21.1"
unsup = "1.1.6"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
