name = "Maddy Origins SMP Redux"
author = "Maddy"
version = "0.1.40"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4fcfb92c7818d56e9e33666707853d5f573625a63c115dd3eef44243c7e183a7"

[versions]
fabric = "0.17.2"
minecraft = "1.21.1"
unsup = "1.1.6"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
