name = "Maddy Origins SMP Redux"
author = "Maddy"
version = "0.1.15"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a7e5a77200fe62c4f9b13b49f63eb3fe22a46db8457aa69186b549ccfbf89b60"

[versions]
fabric = "0.17.2"
minecraft = "1.21.1"
unsup = "1.1.6"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
