name = "Maddy Origins SMP Redux"
author = "Maddy"
version = "0.2.11"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "aae8bffac9b435f55c4ba416b265df011fbd6fddf0d5f92e1dee10f99cd44c06"

[versions]
fabric = "0.17.2"
minecraft = "1.21.1"
unsup = "1.1.6"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
