name = "Maddy Origins SMP Redux"
author = "Maddy"
version = "0.1.59"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "980b38f6f60286d57f2ade71d317bcf857c93a737395ec105ff71062a60d10c7"

[versions]
fabric = "0.17.2"
minecraft = "1.21.1"
unsup = "1.1.6"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
