name = "Maddy Origins SMP Redux"
author = "Maddy"
version = "0.1.71"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5c323db5994e0656c6b1ad161a79e4e674dbdd69ee670da6e9500dedf9df48c1"

[versions]
fabric = "0.17.2"
minecraft = "1.21.1"
unsup = "1.1.6"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
