name = "Maddy Origins SMP Redux"
author = "Maddy"
version = "0.1.20"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8ab4428d54fdca4fa054dfce12d22539ded414aa6234851d3c3d3f28c13583f1"

[versions]
fabric = "0.17.2"
minecraft = "1.21.1"
unsup = "1.1.6"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
