name = "Maddy Origins SMP Redux"
author = "Maddy"
version = "0.1.51"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "da6f86164b7118951d799e82849eb42fb743a25dbde0783c797491f1f0060b33"

[versions]
fabric = "0.17.2"
minecraft = "1.21.1"
unsup = "1.1.6"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
