name = "Maddy Origins SMP Redux"
author = "Maddy"
version = "0.1.14"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8293df96360e10bdcf872bc6e2b04881a3a68eef2bd460a0292b98d59356f850"

[versions]
fabric = "0.17.2"
minecraft = "1.21.1"
unsup = "1.1.6"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
