name = "Maddy Origins SMP Redux"
author = "Maddy"
version = "1.0.27"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e77dbf5eeed95fd5fa233e474e2e3642ee3e16fde0e73571b6c32dfd448f7494"

[versions]
fabric = "0.17.2"
minecraft = "1.21.1"
unsup = "1.1.6"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
