name = "Maddy Origins SMP Redux"
author = "Maddy"
version = "0.1.70"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "48c57c5ba9ed4de2602a67fa495d531643d7b7074861af288b83615406c5b0fc"

[versions]
fabric = "0.17.2"
minecraft = "1.21.1"
unsup = "1.1.6"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
