name = "Maddy Origins SMP Redux"
author = "Maddy"
version = "0.1.55"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dcb7d41a237adef5ce46f6f5e307873cf4ee0f0612df5d1955b0068e5b052b6c"

[versions]
fabric = "0.17.2"
minecraft = "1.21.1"
unsup = "1.1.6"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
