name = "Maddy Origins SMP Redux"
author = "Maddy"
version = "0.1.8"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "df175a957b3be8eb7fbc03f4364b78ff8d138770219b4858b0577e15d3592c79"

[versions]
fabric = "0.17.2"
minecraft = "1.21.1"
unsup = "1.1.6"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
