name = "Maddy Origins SMP Redux"
author = "Maddy"
version = "0.1.12"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "614811b450015f45b06e71f698becb4f141f26ba98075b37020acad58631a0ad"

[versions]
fabric = "0.17.2"
minecraft = "1.21.1"
unsup = "1.1.6"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
