name = "Maddy Origins SMP Redux"
author = "Maddy"
version = "0.1.22"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9d0307201714796d78f3d57e26a4f548e9413d02461c4844dc080e5aed28c7ee"

[versions]
fabric = "0.17.2"
minecraft = "1.21.1"
unsup = "1.1.6"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
