name = "Maddy Origins SMP Redux"
author = "Maddy"
version = "0.1.26"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "99e06ea36b41f22af4381f194487f2b6e3bccd9ba53803307f44c28c3cb402aa"

[versions]
fabric = "0.17.2"
minecraft = "1.21.1"
unsup = "1.1.6"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
