name = "Maddy Origins SMP Redux"
author = "Maddy"
version = "0.1.86"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "478e06e19ada3966a6b224b7de33d9062923f6dc65c2e488ece3ae507711be23"

[versions]
fabric = "0.17.2"
minecraft = "1.21.1"
unsup = "1.1.6"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
