name = "Maddy Origins SMP Redux"
author = "Maddy"
version = "0.1.81"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0278a6a4ea157ac2fa3dc277bc6cab583861d2dd74eb5c7b283c84855cb08105"

[versions]
fabric = "0.17.2"
minecraft = "1.21.1"
unsup = "1.1.6"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
