name = "Maddy Origins SMP Redux"
author = "Maddy"
version = "0.2.17"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "74b55e58afed2cefb20744df3e12a77c83060560cfe745bca5c66a896877b634"

[versions]
fabric = "0.17.2"
minecraft = "1.21.1"
unsup = "1.1.6"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
