name = "Maddy Origins SMP Redux"
author = "Maddy"
version = "0.1.74"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bb6043a08efb9d286fc6b17e9fe4ddca848d65702c4d6a5135e3d3b76a852ba3"

[versions]
fabric = "0.17.2"
minecraft = "1.21.1"
unsup = "1.1.6"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
