name = "Maddy Origins SMP Redux"
author = "Maddy"
version = "0.1.17"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cfe461d08b5df27a787773a335614f3a121b36abf4128f7520088c53670199f4"

[versions]
fabric = "0.17.2"
minecraft = "1.21.1"
unsup = "1.1.6"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
