name = "Maddy Origins SMP Redux"
author = "Maddy"
version = "0.1.46"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c65faff6620f71ce36f57159ef3e613bd0aadc1583b4425c34e3ffa986677002"

[versions]
fabric = "0.17.2"
minecraft = "1.21.1"
unsup = "1.1.6"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
