name = "Maddy Origins SMP Redux"
author = "Maddy"
version = "0.1.58"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a04b6ced7d9d059b8d6399ca5b26a540bfb145689ea771a386f94cba86c7db6d"

[versions]
fabric = "0.17.2"
minecraft = "1.21.1"
unsup = "1.1.6"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
