name = "Maddy Origins SMP Redux"
author = "Maddy"
version = "0.2.20"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "73423a70a20b821d8a4aaa1c4416099d9e856e3b196481fe980375309acd30ad"

[versions]
fabric = "0.17.2"
minecraft = "1.21.1"
unsup = "1.1.6"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
