name = "Maddy Origins SMP Redux"
author = "Maddy"
version = "0.1.67"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "52f7bbe3e5b30c6c5167a505345aa842ff44110dd243b511f00e00e1ecbd64bb"

[versions]
fabric = "0.17.2"
minecraft = "1.21.1"
unsup = "1.1.6"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
