name = "Maddy Origins SMP Redux"
author = "Maddy"
version = "0.2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d93250ce536a2980bcf65b63242d0fc651b981b24fcb837b8611ff3fd68ade92"

[versions]
fabric = "0.17.2"
minecraft = "1.21.1"
unsup = "1.1.6"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
