name = "Maddy Origins SMP Redux"
author = "Maddy"
version = "0.1.80"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "add071ecbf57d35a513e7f4819a8116f3edfb69cae1a84c140e86703c593ff3e"

[versions]
fabric = "0.17.2"
minecraft = "1.21.1"
unsup = "1.1.6"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
