name = "Maddy Origins SMP Redux"
author = "Maddy"
version = "0.2.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6d64b3fb747b77f2cfc03ec1eb66806b23f174ce714021cabb77816a4e536149"

[versions]
fabric = "0.17.2"
minecraft = "1.21.1"
unsup = "1.1.6"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
